package pow

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestFrontendWorkerParity verifies a solution produced by the browser
// worker's logic against the backend, using a vector generated by running
// that logic under Node with SubtleCrypto.
//
// The worker previously short-circuited on hash[0] != 0 before applying
// the real difficulty test, so it rejected valid solutions whenever
// difficulty < 8. Production difficulty is 22, which hid it. This pins the
// two implementations to the same rule.
func TestFrontendWorkerParity(t *testing.T) {
	p := &TokenPayload{
		Version: 1, Mode: "generic", Algorithm: "sha256",
		Path: "/t.iso", Timestamp: 1, ExpiresAt: 2,
		Difficulty: 8, Counter: "000000000000007f", Salt: "s",
	}

	const wantCanonical = "mirrors-pow-v1\nmode=generic\nip=\npath=/t.iso\nts=1\nexp=2\n" +
		"difficulty=8\ncnt=000000000000007f\nsalt=s\n"
	require.Equal(t, wantCanonical, BuildCanonicalInput(p),
		"canonical layout must match what the frontend builds")

	const wantSign = "009c5b86483600214df45926109b0a4cb343ef56e6a54827473ec18a8c170e12"
	assert.Equal(t, wantSign, ComputeSign(p),
		"the sign the worker posts must be the one the backend computes")

	assert.True(t, HasLeadingZeroBits32(HashCanonical(wantCanonical), 8),
		"the solution the worker accepted must satisfy the backend's difficulty check")
}

// TestHasLeadingZeroBits_SubByteDifficulty covers the range the old worker
// got wrong: a first byte that is non-zero can still satisfy a difficulty
// below 8.
func TestHasLeadingZeroBits_SubByteDifficulty(t *testing.T) {
	for _, tc := range []struct {
		name string
		b0   byte
		n    int
		want bool
	}{
		{"0x0F meets 4 bits", 0x0F, 4, true},
		{"0x3F meets 2 bits", 0x3F, 2, true},
		{"0x0F fails 5 bits", 0x0F, 5, false},
		{"0xFF fails 1 bit", 0xFF, 1, false},
		{"zero byte meets 8 bits", 0x00, 8, true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			h := make([]byte, 32)
			h[0] = tc.b0
			assert.Equal(t, tc.want, HasLeadingZeroBits(h, tc.n))
		})
	}
}
